name: smart_home
description: HOME-ES
publish_to: "none"
version: 2.2.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  # better_player:
  #   path: patched_packages/better_player
  media_kit: ^1.1.10
  media_kit_video: ^1.2.5
  media_kit_libs_android_video: ^1.0.5
  # flutter_secure_storage: ^9.2.2
  dio: ^5.6.0
  flutter_secure_storage: ^9.0.0
  webview_flutter: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true

  # Fallback зураг (хоёуланд — зарим лаунчер/олдворуудад хэрэгтэй)
  image_path: assets/icons/home-es_icon.png

  # iOS тусгай тохиргоо
  remove_alpha_ios: true
  ios_icon_name: "AppIcon"

  # Android adaptive icon давхаргууд (эдгээр PNG-үүдээ төслийнхөө assets руу хуул)
  adaptive_icon_background: assets/icons/android/ic_background.png
  adaptive_icon_foreground: assets/icons/android/ic_foreground.png
  adaptive_icon_monochrome: assets/icons/android/ic_monochrome.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/pbd_view_v2.html
